name: Generate Snake Game

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Generate Snake Game
        uses: Platane/snk@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push generated Snake game to the output branch
        run: git push
